services:
  - type: web
    name: mia10-tp2-reconocedor-voz
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: FLASK_ENV
        value: production